version: '3'
services:
  main:
    build: .
    container_name: rpi-ncsdk-docker
    restart: on-failure
    privileged: true
    working_dir: /ncsdk
    network_mode: host
    volumes:
      - '/dev/bus/usb/:dev/bus/usb/:ro,rslave'
    command: >
      python3
      -c
      'import tensorflow as tf;
      import mvnc.mvncapi as mvnc;
      print("TF_VERSION:", tf.__version__);
      print("NCAPI Version:"", mvnc.global_get_option(mvnc.GlobalOption.RO_API_VERSION))'

